### ISSUE TITLE
CAH-0004: [Requirement] Card Czar Shall Play Black Card

### ISSUE THREAD

**Issue by TeamHaircut** [TeamHaircut/CAH#3]
Description:
At the start of the game one player will be designated as the Card Czar. Initially, the Card Czar can be chosen randomly, or is user defined. The Card Czar can have a different card view, and will have different functions than the other connected users

Notes:

Related Documentation or Issues:

- [x]  Create [CAH-0004: [New Feature] Draw Black Card as Card Czar](https://github.com/TeamHaircut/CAH/issues/11)
- [x]  Create [CAH-0005: [New Feature] View Black Card from Card Czar Client UI](https://github.com/TeamHaircut/CAH/issues/12)
- [x]  Create [CAH-0013: [New Feature] Card Czar Broadcasts Black Card to Group](https://github.com/TeamHaircut/CAH/issues/13)

Version/Commit: 0.1

**Comment by TeamHaircut** [comment]
closed with CAH-0013
